---
BuyShipCommand: "/buyship"
ShipSellers:
- Name: Bob
  Origin: -1
  BoundingBox:
    Playfield: Akua
    Rect:
      min:
        x: -16000
        y: 0
        z: 7500
      max:
        x: -14000
        y: 100
        z: 8000
  ShipsForSale:
  - DisplayName: Ship One
    BlueprintName: SV_Viper   # Name of a file (minus extension) from the Content\Prefabs folder
    EntityType: SV
    ShipNameFormat: "Cool ship1 for {0}"
    MessageToShowOnPurchase: "Look outside for your new ship!"
    Price: 100.50
    SpawnLocation:
      x: -15434
      y: 68
      z: 7689
  - DisplayName: Ship Two
    BlueprintName: SV_PF2
    EntityType: CV
    ShipNameFormat: "Cool ship2 for {0}"
    MessageToShowOnPurchase: "Look outside for your new ship!"
    Price: 2000.50
    SpawnLocation:
      x: -1439
      y: 149
      z: 707.5
- Name: Bobby
  Origin: -1   # -1 means any player can buy
  BoundingBox:
    Playfield: Akua
    Rect:
      min:
        x: -1439
        y: 49
        z: 707.5
      max:
        x: -1437.7
        y: 51
        z: 710
  ShipsForSale:
  - DisplayName: Shipp One
    BlueprintName: SV_PF1
    EntityType: SV
    ShipNameFormat: "Cool ship1 for {0}"
    MessageToShowOnPurchase: "Look outside for your new ship!"
    Price: 100.50
    SpawnLocation:
      x: -1439
      y: 149
      z: 707.5
  - DisplayName: Shipp Two
    BlueprintName: SV_PF2
    EntityType: CV
    ShipNameFormat: "Cool ship2 for {0}"
    MessageToShowOnPurchase: "Look outside for your new ship!"
    Price: 2000.50
    SpawnLocation:
      x: -1439
      y: 149
      z: 707.5
